services:
  xui:
    build: .
    container_name: xuione
    hostname: xuione
    restart: unless-stopped
    privileged: true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "2086:2086"
      - "8000:8000"
      - "25461:25461"
    volumes:
      - xui_data:/home/xui
      - mysql_data:/var/lib/mysql
    environment:
      - TZ=UTC
    ulimits:
      nofile:
        soft: 655350
        hard: 655350

volumes:
  xui_data:
    name: xui_home
  mysql_data:
    name: xui_mysql
